name: selfDevelopment
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  flutter_svg: ^0.19.0
  equatable: ^1.2.5
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  get_it: ^5.0.1
  json_annotation: ^3.0.1
  loader_overlay: ^1.1.0+1
  pull_to_refresh: 1.6.3
  shared_preferences: ^0.5.12+2
  image_picker: 0.6.7+22
  dartz: ^0.9.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
